version: "3.8"

services:
  nasm-tp1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nasm-tp1
    image: nasm-tp1:0.1
    volumes:
      - .:/app   # Volume permettant de développer en local et exécuter du code dans le conteneur en exécution.
    stdin_open: true 
    tty: true
    networks:
      - NASM-tp1-net

networks:
  NASM-tp1-net:
      name: NASM-tp1-net
      external: false

volumes:
  nasm-tp1:
    external: false